spring:
  application:
    name: special-lecture
  sql:
    init:
      mode: never
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    show-sql: true
  logging:
    level.org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE
