INSERT INTO lecture(id, title, lecturer, start_date, end_date, capacity) VALUES (default, 'SPRING JPA', 'test1', '2024-10-01 00:00:00', '2024-10-30 00:00:00', 30);
INSERT INTO lecture(id, title, lecturer, start_date, end_date, capacity) VALUES (default, 'SPRING WEB', 'test1', '2024-10-01 00:00:00', '2024-10-30 00:00:00', 30);
INSERT INTO lecture(id, title, lecturer, start_date, end_date, capacity) VALUES (default, 'SPRING TEST', 'test2', '2024-09-01 00:00:00', '2024-09-10 00:00:00', 30);
INSERT INTO lecture(id, title, lecturer, start_date, end_date, capacity) VALUES (default, 'SPRING JPA 2', 'test2', '2024-10-04 00:00:00', '2024-10-30 00:00:00', 30);
INSERT INTO lecture(id, title, lecturer, start_date, end_date, capacity) VALUES (default, 'SPRING JPA 3', 'test2', '2024-10-15 00:00:00', '2024-10-30 00:00:00', 30);
INSERT INTO lecture(id, title, lecturer, start_date, end_date, capacity) VALUES (default, 'SPRING JPA 4', 'test2', '2024-10-16 00:00:00', '2024-10-30 00:00:00', 30);
insert into student (id, name) values (default, 'Edin Bernhardi');
insert into student (id, name) values (default, 'Ariela Richard');
insert into student (id, name) values (default, 'Dotti Paragreen');
insert into student (id, name) values (default, 'Ernestus Ody');
insert into student (id, name) values (default, 'Edna Anton');
insert into student (id, name) values (default, 'Elwood Cosgry');
insert into student (id, name) values (default, 'Corey Pierson');
insert into student (id, name) values (default, 'Ivette Chaikovski');
insert into student (id, name) values (default, 'Latashia Ragsdall');
insert into student (id, name) values (default, 'Jason Pay');
insert into student (id, name) values (default, 'Jemimah Kabos');
insert into student (id, name) values (default, 'Cristie Emmerson');
insert into student (id, name) values (default, 'Torrence Matteoli');
insert into student (id, name) values (default, 'Helsa Straneo');
insert into student (id, name) values (default, 'Johna Vernall');
insert into student (id, name) values (default, 'Dael Restill');
insert into student (id, name) values (default, 'Karlotta Awde');
insert into student (id, name) values (default, 'Bianca Rowett');
insert into student (id, name) values (default, 'Annette Steade');
insert into student (id, name) values (default, 'Magda Willoughey');
insert into student (id, name) values (default, 'Alberto Couche');
insert into student (id, name) values (default, 'Manfred Feldhammer');
insert into student (id, name) values (default, 'Emmerich Pimerick');
insert into student (id, name) values (default, 'Weidar Danilevich');
insert into student (id, name) values (default, 'Elene Deverale');
insert into student (id, name) values (default, 'Milly Bushrod');
insert into student (id, name) values (default, 'Mahala Burgett');
insert into student (id, name) values (default, 'Kassie Kenrat');
insert into student (id, name) values (default, 'Nertie Brandacci');
insert into student (id, name) values (default, 'Stepha Loach');
insert into student (id, name) values (default, 'Marjory Jonke');
insert into student (id, name) values (default, 'Francklyn Pacher');
insert into student (id, name) values (default, 'Ferdinande Abbotts');
insert into student (id, name) values (default, 'Kara-lynn Brimfield');
insert into student (id, name) values (default, 'Lanae Zelland');
insert into student (id, name) values (default, 'Brinna Franceschielli');
insert into student (id, name) values (default, 'Clark Letts');
insert into student (id, name) values (default, 'Annadiana Veal');
insert into student (id, name) values (default, 'Kirsten Sykora');
insert into student (id, name) values (default, 'Jennica Bonome');
